In [1]:
print("Hi Azeem!")

Hi Azeem!


In [3]:
import sys
print(sys.version)

3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]


In [7]:
import math as m
a = 25
b = 10
print("The square root of a:",m.sqrt(a))
print("The sin value of b:",m.sin(b))

The square root of a: 5.0
The sin value of b: -0.5440211108893698


In [2]:
import numpy as np
first_array = np.array([1,2,3])
print (first_array)

[1 2 3]


In [3]:
second_array = np.array([2,3,4])
print (second_array)

[2 3 4]


In [5]:
oneD_array = np.arange(2)

In [6]:
print (oneD_array)

[0 1]


In [2]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
np.array ([[1,2,3],[5,6,7]])

array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
np.array ([[1,2,3],[5,6,7]]),([[1,2,3],[5,6,7]])

(array([[1, 2, 3],
        [5, 6, 7]]),
 [[1, 2, 3], [5, 6, 7]])

In [2]:
import numpy as np
A = np.array([[1,2,3],[2,2,3]])
B = np.array([4,5,6])

np.add(A,B)

array([[5, 7, 9],
       [6, 7, 9]])

In [3]:
np.subtract(B,A)

array([[3, 3, 3],
       [2, 3, 3]])

In [4]:
np.multiply(A,B)

array([[ 4, 10, 18],
       [ 8, 10, 18]])

In [5]:
np.divide(A,B)

array([[0.25, 0.4 , 0.5 ],
       [0.5 , 0.4 , 0.5 ]])

In [7]:
np.power(A,2)

array([[1, 4, 9],
       [4, 4, 9]], dtype=int32)

In [9]:
np.power(A,B)

array([[  1,  32, 729],
       [ 16,  32, 729]])

In [10]:
import numpy as np
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.where(x%2==0,'Even','Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [14]:
condlist = [x<5,x>5]
checklist = [x**2,x**3]

np.select(condlist,checklist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [16]:
import numpy as np
arr = ([[1,2,3],[5,6,7],[7,9,1]])
arr

[[1, 2, 3], [5, 6, 7], [7, 9, 1]]

In [17]:
np.min(arr)

1

In [18]:
np.amin(arr,axis = 0)

array([1, 2, 1])

In [19]:
np.max(arr)

9

In [20]:
np.max(arr,axis = 0)

array([7, 9, 7])

In [21]:
np.mean(arr)

4.555555555555555

In [22]:
np.median(arr)

5.0

In [23]:
np.std(arr)

2.7532248207475263

In [24]:
np.var(arr)

7.580246913580248

In [25]:
np.percentile(arr,50)

5.0

In [26]:
deg = np.array([0,30,45,60,90])
np.sin(deg*np.pi/100)

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [28]:
np.cos(deg*np.pi/100)

array([ 1.        ,  0.58778525,  0.15643447, -0.30901699, -0.95105652])

In [29]:
np.tan(deg*np.pi/100)

array([ 0.        ,  1.37638192,  6.31375151, -3.07768354, -0.3249197 ])

In [30]:
np.floor(arr)

array([[1., 2., 3.],
       [5., 6., 7.],
       [7., 9., 1.]])

In [2]:
import pandas as pd
l = [x for x in range(5)]

In [3]:
l

[0, 1, 2, 3, 4]

In [6]:
s = pd.Series(l)

In [7]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [8]:
s[2]

2

In [9]:
s = pd.Series(l,index = ['a','b','c','d','e'])

In [10]:
s

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [4]:
import pandas as pd
df = pd.DataFrame()
type(df)
pd.core.frame.DataFrame
df = pd.read_csv('C:/Users/Admin/Downloads/1642057416_lesson5retail_mart_management_datasets (1)/Lesson 5 - Retail_Mart_Management_Datasets/sales_datasets')

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Admin/Downloads/1642057416_lesson5retail_mart_management_datasets (1)/Lesson 5 - Retail_Mart_Management_Datasets/sales_datasets'